version: '3.7'
services:
  sslh:
    image: registry-bzh.alfred.cafe/breizh-ctf-2023/breizh-ctf-2023/sslh
    command: --listen=0.0.0.0:1337 --openvpn=127.0.0.1:1194 --http=127.0.0.1:30000
    ports:
      - 1337:1337
      - 2222:22

  openvpn:
    build:
      context: ./openvpn
      dockerfile: openvpn.Dockerfile
    network_mode: service:sslh
    cap_add:
      - NET_ADMIN

  dofus:
    build: .
    network_mode: service:sslh
    volumes:
      - ./app:/var/www/html
