apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-janitor
  namespace: default
# example rules configuration to set TTL for arbitrary objects
# see https://codeberg.org/hjacobs/kube-janitor for details
data:
  rules.yaml: |
    rules:
      - id: dynamic-challenge-cleanup
        # remove deployments and statefulsets without a label "application"
        resources:
          - deployments
          - ingressroutes
          - ingressroutetcps
          - services
          - ingresses
        # see http://jmespath.org/specification.html
        jmespath: "metadata.namespace == 'dynamic-challenges'"
        ttl: 8h
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-janitor
    version: v23.2.0
  name: kube-janitor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-janitor
  template:
    metadata:
      labels:
        application: kube-janitor
        version: v23.2.0
    spec:
      serviceAccountName: kube-janitor
      containers:
      - name: janitor
        # see https://codeberg.org/hjacobs/kube-janitor/releases
        image: hjacobs/kube-janitor:23.2.0
        args:
          # run every minute
          - --interval=60
          - --debug
          - --rules-file=/config/rules.yaml
          - --include-resources=deployments,ingressroutes,ingressroutetcps,services,ingresses
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: kube-janitor
