version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  blockchain:
    build: ./blockchain
    network_mode: service:nginx
